### ISSUE TITLE
Reclassify ERRORS to WARNINGS when invalid header is detected and display relevant file

### ISSUE THREAD

**Issue by gilbertoca** [jbake-org/jbake#179]
jbake or jbake -b should stop on first occurrence of any ERROR, for example:

    ERROR org.jbake.app.Parser - Error parsing meta data from header!

**Comment by jonbullock** [comment]
I'm not so sure about this one, especially given your example, as it would mean the only files you could store in the content folder is working content, you couldn't have anything as a work in progress in there.

The current behaviour is also by design, to allow you to see all errors from your project/site in one go without having to go through a cycle of run-fix over and over again.

Perhaps the classification of errors should be improved as, looking at your example now, that should really be WARNING rather than ERROR.

**Comment by gilbertoca** [comment]
How can we see the line and the error type - something wrong occurred but I don't know what?

**Comment by jonbullock** [comment]
That's the information that's lacking at the moment and will be addressed as part of #174.

**Comment by gilbertoca** [comment]
You can use my project [1] to test this feature. I've converted my blog [2] using the wordpress-to-jekyll-exporter, but the result was not good enough for jbake as you can see here #178 .

[1] https://github.com/gilbertoca/gilbertoca.com
[2] blog.gilbertoca.com
[3] https://github.com/benbalter/wordpress-to-jekyll-exporter

**Comment by jonbullock** [comment]
Thanks Gilberto, I will do.
