### ISSUE TITLE
Parsing of first header line fails if using UTF-8 with BOM

### ISSUE THREAD

**Issue by mgwerder** [jbake-org/jbake#257]
When using an UTF-8 encoded document with BOM parsing of the first header line seems to fail. 

This has been observed with JBake v2.4.0 (2015-05-30 19:08:27PM) and the groovy template. The first tag was "title" and it was set to null. No other templates have been analyzed.

Btw. Keep up the good work.

**Comment by jonbullock** [comment]
Thanks for reporting this @mgwerder could you provide an example file and the stacktrace you see?

**Comment by ventooUser** [comment]
Sorry for not answering. I must have somehow missed the notification. The problem is not dramatical and it is easy to circumvent if you are aware of it. I attached a zip file ([example.zip](https://github.com/jbake-org/jbake/files/748426/example.zip)) containing two versions of the same document. They look identical in an UTF-8 Aware Editor. However the working example (without BOM) Shows the title (first line of file) and the non-working example Shows "null" as title. A stack trace is not dumped when baking. I assume that the BOM is interpreted as part of the first line.

As far as I have [read](http://www.unicode.org/faq/utf_bom.html#BOM) the BOM in UTF-8 is always three Bytes (EF BB BF) and may or may not be present in a UTF-8 document . The behaveour is document in two bugs in the java database [here](http://bugs.java.com/view_bug.do?bug_id=4508058) and  [here](http://bugs.java.com/view_bug.do?bug_id=6378911) and set to "won't fix" as it could break existing applications. The easiest workarround is to discard the first three Bytes of a file if they match "EF BB BF". 

I can confirm that the issue still exists in 2.5.0 and I have built 2.5.1 from github and can confirm the issue there as well.

Regards
Martin
