### ISSUE TITLE
Any progress on the project? A new release anytime soon?

### ISSUE THREAD

**Issue by ieugen** [jbake-org/jbake#268]
Hello, 

I've decided to use JBake for my sites and I am wondering if this was a good decision. I like some of the features and I would like to see more. I have a few ideas about stuff that I would like to contribute - like continuous site building etc, but I haven't seen a lot of activity. 

I see pull requests with features piling up and people discussing but no new releases. The last release was more than half a year ago. 

I don't wish to be disrespectful or anything, I am just expressing my concerns about the project. Do you need any help with contributions? Should I go and fork the project to provide the features I need? 

Thanks,

**Comment by jonbullock** [comment]
I hope you find it was a good decision to use JBake :smile: 

If by continuous site building you mean a watch mode so any change to a content file triggers a re-render then this is already in available see #183.

Ultimately I'm the bottle neck on the next release at the moment as I don't have as much free time to spend on the project as I once did. However that will change pretty soon, but in the meantime I'm happy to accept any offers of help.

Have a look at the outstanding issues for v2.5.0 and let me know what you'd like to work on so I can bring you up to speed.

**Comment by ieugen** [comment]
Hi, 

Thanks for the response and it's good to know you're still working on the project. 
I would like to see faster website build times first and maybe a move to Java 7 to add watch. It takes a huge amount of time to develop websites right now since the change->build->view results cycle is very long (~10s).

I also propose jbake adopts git flow for development with multiple branches:

- master is maintenance branch for production
- develop is where the new release forms, and where we can merge pull requests safely
- people can work on feature branches (or their own repos) and merge pull requests faster in develop

NOTE: names can be different 

It would help to have a nightly build or latest build available for download off of develop. I think travis and bintray.com can help with that. 

This way people can test out the next version much more easily. Once the features reach maturity level we can ship a stable release. 

[1] http://nvie.com/posts/a-successful-git-branching-model/
[2] https://docs.travis-ci.com/user/deployment/bintray

**Comment by marcobehler** [comment]
@jonbullock 

Maybe I can help. What are the 3 top things I or anyone really could work on? Feel free to bring me up to speed.

**Comment by jonbullock** [comment]
@ieugen I like the idea of adopting that workflow, could you raise a separate issue for that?

@marcobehler I'll review the outstanding work and get back to you ASAP.

**Comment by haumacher** [comment]
@ieugen In my opinion, watch mode is not sufficient, since it heavily depends on the templates, which pages have to be rebuilt if a single file changes. If you built a menu structure, where a link to every other page is embedded in the source of all pages, almost all pages have to be rebuilt if a single page changes. To circumvent this problem, I built on-demand page rendering in servlets some time ago on a branch (see https://github.com/haumacher/jbake/tree/wikibake/src/main/java/org/jbake/launcher). In dev mode, this option renders pages at the time the page is requested by the browser. This gives an almost zero turn around time for the edit-view cycle. Unfortunately, the `wikibake` branch got already unmergable due to refactorings in the master branch.

**Comment by ieugen** [comment]
@haumacher I agree that for different use case not all things will work as good as they can/should.

For my use cases rebuilding the whole website is fine and fast enough. It's a feature I can use - I have ~2s build time which is great compared to 10s. 

Now, there might be better solutions out there, like yours, and I think that they should be adopted as well. One does not exclude the other in my opinion. 

Sorry for the merging part. Hopefully this will change in the future by adopting a more reliable/transparent process for merging new features and making releases. 

p.s.  One of the principles I follow is to delive Value. To me having a faster build is valuable. It doesn't mattre much what the technical solution is. The simpler the better. 

Best regards,

**Comment by mgfeller** [comment]
I would just like to express my support and thanks for JBake and its community. I've decided to use JBake for my personal site, and consider introducing it at work too. However, I'm also concerned about the progress of the project and PR's piling up. I'm slightly hesitant to use JBake because of this. 

Of course, I don't wish to be disrespectful either, I understand that there is a lot of work behind maintaining a project like this properly, and we all have a lot to do. I'd like to be part of the JBake community and contribute. It would be nice to see gitflow as development process to facilitate more frequent releases easily.

**Comment by jonbullock** [comment]
Thanks @mgfeller and @ieugen for taking the time to raise your concerns - I have taken them onboard and action will be taken to address them.
