### ISSUE TITLE
Images from content folder are not copied to output folder

### ISSUE THREAD

**Issue by halyph** [jbake-org/jbake#281]
I've just started using jbake and have the next issue.
It is very convenient to have adoc files and related images collocated in the same folder. E.g nice github rendering feature is supported out of the box. Also, atom editor, asciidocfx support image rendering when they are in the same folder.

But, jbake does not copy images from `content` folder to `output` folder. I've been using default settings.

Could you please clarify if this issue can be fixed via some settings? Or it is require jbake modification?

**Comment by jonbullock** [comment]
To achieve this you should place the images into a folder structure underneath assets that matches what you have under content.

**Comment by manikmagar** [comment]
@jonbullock I am keeping my jbake template and blog content in separate github repos intentionally. That gives me ability to change my template easily. I indeed planned to have content images in my content repo. I did not realize that images will not get copied while baking. Personally I think it should be allowed as I can see a clear benefit from it which is segregation of a template and content. Do you think this feature can be added to copy any static content from contents directory to output?

**Comment by haumacher** [comment]
@manikmagar  This question seems not to be much about sparation of template and content, but enforced separation of text content and image content.

When baking the source structure is required to be 

```
project
 +-- assets
 |       +-- somefolder
 |               +-- myImage.jpg
 +-- content
         +-- somefolder
                 +-- myPageReferingMyImage.md
```
This structure is really hard to maintain, if the folder structure is deep and images are closely related to content pages. One has to duplicate the `content` folder structure under the `assets` directory. This has the additional drawback mentioned by @halyph that when browsing the repository in Github, all image references are broken, because the Github viewer expects images in the same directory as the content. 

@jonbullock  Therefore, I'm supporting @halyph's RFE to allow placing assets directly in the `contents` folder and copying everything that is not processed by JBake directly to the output folder.

**Comment by manikmagar** [comment]
@haumacher I forgot to mention I consider images related to post as content, in that sense I mentioned separation. I think templates (a.k.a. themes) and contents (text as well images related to text) should be allowed to manage seperately. `assets` folder can very well be used to keep any common images related to the template. For example, If I am using a background image on my header, I am ok to keep that in the `assets` because when I change my template from A to B, that image may not be relavant to template B.

Now, if I have a post (written in md or in any format) and I have 2 images inline to that post and are post-specific then I wouldn't want to store those inside `assets` directory because when I change my template, `assets` will be a mix of template as well content-related resources and thus will require more efforts to maintain (like @haumacher, you said its difficult to maintain).

I didn't think about drawback mentioned by @halyph but now I realize I agree with that drawback. Especially when I am going to manage my content as a separate github repo, if someone visits the repo and see my content referencing `/images/.....` but don't see them, it misleading and not good.

@jonbullock I think JBake should allow copying non-processed folders to output. May be something like, expose a property `output.static.prefix` and if I set `output.static.prefix=images` then copy the `/content/images` folder to `output`. Offcourse, there can be other way of doing it based on how JBake should process those static resources. By that I mean, should that folder be always replaced in output or JBake should track what is changed like it does for content (IMHO, to keep it simple, I am ok to have static folder replaced all the time).

**Comment by jonbullock** [comment]
Thanks @manikmagar and @haumacher for sharing your thoughts on this topic and @halyph for raising this. I'll look to add this in the next release (after 2.5.0) once I've given it some more thought, as there is a related suggestion to ignore certain folders (with a dot prefix etc.) from baking.

**Comment by gregopet** [comment]
I support this suggestion entirely, assets related to the article belong next to the article text. Multiple people write articles for our page and the cleanest way is to just tell them to go create a folder and stick all their content in there - I wish there was a way to simply put the source files under `src` (or whatever we decide to call it) instead of having to tell people to open `src/jbake/content`. I know it sounds trivial but it really isn't to people who don't care that there is a JBake somewhere in there.

I'm simply copying the assets with Gradle:

````groovy
task copyNonDocs(type: Copy) {
	from 'src/jbake/content'
	into 'build/jbake'
	exclude '**/*.adoc', '**/*.md', '**/*.html'
}
tasks.bake.dependsOn copyNonDocs
````

The `copyNonDocs` task is fired first, copying all assets over, then `bake` is triggered, copying the HTML files next to or over the files copied previously.

**Comment by jonbullock** [comment]
@gregopet Using the JBake Gradle plugin, you should be able to set whatever source folder you like: https://github.com/jonbullock/gradle-jbake-site/blob/master/build.gradle#L30

And you can alter the config that specifies 'content' as the folder to look in.

**Comment by gregopet** [comment]
I had to upgrade the plugin version but it works now, thank you!

**Comment by SiddheshRane** [comment]
I too feel that having to separate post related images into a similar but separate folder stucture is an inconvenient restriction placed by JBake. We already have header information to tell JBake what files to process as content so I think a natural solution is to just merge the assets and content folder into one.

**Comment by SiddheshRane** [comment]
An easy hack right now if you wish to keep post related assets in the content folder is to set the `assets` folder the same as `content` folder using `asset.folder=content` property in `jbake.properties` .
Have a look at [my example jbake.properties](https://github.com/SiddheshRane/blog/blob/master/jbake.properties#L12) file. 
This way my images are right next to asciidoc content. My site structure gets less tied to JBake.

**Comment by jonbullock** [comment]
Interesting idea... I hadn't thought of doing that. 

I've not tried it myself yet but doesn't your source content files get copied over to the output folder by the asset processing stage?

**Comment by SiddheshRane** [comment]
@jonbullock yes the original source gets copied to the destination folder. Its not a problem in most cases, except when your source is in `html`. Then your rendered html output gets overwritten by the original source because assets copying seems to be the last stage. If assets are copied first then such a use case as mine gets addressed.

I firmly believe that content folder should be allowed to have static resources. JBake should try to impose as little structure as possible, which was one of the many reasons I didn't go ahead with Jekyll.

**Comment by jonbullock** [comment]
Thanks for clarifying @SiddheshRane 

The aim is to allow static files in the content folder in the next release.

**Comment by uptimestar** [comment]
So is this now best practice, to use content and asset folder to be same?

**Comment by manikmagar** [comment]
That depends on what you consider as content and asset. For me, any static resources such as css, js, logo etc goes to assets folder. The images that are part of a blog/article, I prefer to stay side-by-side, usually in images folder at content files. Earlier to maintain the structure, you would have to duplicate all folder structure in assets directory.
