### ISSUE TITLE
Support for authors

### ISSUE THREAD

**Issue by EdwinFLopez** [jbake-org/jbake#288]
Hi. This is more like a question (if can't be achieved, it's a feature request).

We're a team of 3 people and I'd like to see for each one of us, an author profile and a little picture in each one of the post written, pretty much like this theme for bootstrap:
- [adventurethemes - posts](http://adventurethemes.com/demo/writer/html/v2/), 
- [adventurethemes - author profile](http://adventurethemes.com/demo/writer/html/v2/author.html).

Is it possible to acomplish currently? If so, how can I proceed?.

Thanks a lot.

**Comment by manikmagar** [comment]
@EdwinFLopez, may be you can register a new custom page type `author`, define a template for author in jbake.properties `template.users.file=author.ftl`. Design author.ftl to be author's profile page. On post/index, you can refer the authors defined in content model. (You can use any template language instead of ftl). Give it a try.

@melix  had mentioned similar usage here https://github.com/jbake-org/jbake/pull/78#issuecomment-33022517

**Comment by EdwinFLopez** [comment]
I'll try it. Thank you @manikmagar

**Comment by manikmagar** [comment]
You are welcome @EdwinFLopez. If it works, then don't forget to update solution here, it might help someone else looking to do similar thing.

**Comment by manikmagar** [comment]
Just saw this bug #283 where custom types are broken in v2.4.0 so keep a check on that while you try.

**Comment by jonbullock** [comment]
@EdwinFLopez did you achieve what you wanted to by using a custom content type?
