### ISSUE TITLE
When a directory has a dot (".") in it, but the filename doesn't, FileNotFoundException results.

### ISSUE THREAD

**Issue by mtnygard** [jbake-org/jbake#300]
# Situation

My content files are supplied in asciidoc. I have `output.extension` and `outfilesuffix` both set to nothing in jbake.properties.

The target directory has a dot in it. Inside `org.jbake.app.Renderer`, the output file path is truncated at the dot. The renderer then attempts to create a writer on that path. The path happens to refer to a directory, so it passes the file.exists() check, but it is a directory so it can't be opened for writing.
# Expected behavior

Using String.lastIndexOf() to get the file extension is not sufficient. It should only look for the last dot _after_ the last file separator character.

**Comment by mtnygard** [comment]
I have a fix for this, but am having a hard time crafting a test. It needs an output directory with a dot in it (which AbstractTemplateEngineRenderingTest doesn't have in its setup) and a content file without an extension (which the Parser doesn't know how to handle in the tests.)

So far, I've just copied the renderPost test case. (Visible in mtnygard/jbake@656a39ce2b877647d7).

Got any ideas about how to make this less cumbersome?

**Comment by jonbullock** [comment]
Hmm the template engine tests don't lend themselves well to this situation.

For this situation I'd create a separate test case (maybe even a new class) that just tests the Renderer.render method for this specific scenario. We've recently added support into the tests for Mockito which you could use.

**Comment by jonbullock** [comment]
I'm working on v2.5.0 at the moment so if you raise a PR with the fix in I'd be happy to include it in the next release, the test case can always come after in a separate PR.

**Comment by jonbullock** [comment]
Come up with this test for the bug: https://gist.github.com/jonbullock/41dde7da607afe3a78983c984f288693

It requires a new constructor to be added to Renderer which may help other tests long term, the test focuses on testing the logic within Renderer as there are some scenario's that don't have any coverage at the moment so this test class can be expanded upon later on. Comments?

**Comment by ancho** [comment]
Hey Jon,

I think it is good style to make the `DelegatingTemplateEngine` configurable. Testing is much easier that way.

But I wonder if `destination` and `templatesPath` is really necessary, as those two attributes should be present within the `CompositeConfiguration` accessible with `config.getString(Keys.DESTINATION_FOLDER)` and `config.getString(Keys.TEMPLATE_FOLDER)` .

**Comment by ancho** [comment]
How about introducing a `JbakeConfiguration` ?

See https://gist.github.com/ancho/f61643f93d6bdb9a73c90dca32202d3e

**Comment by jonbullock** [comment]
`DelegatingTemplateEngine` needs refactoring as well really as that is what needs `templatesPath` in the real life usage scenario. At the very least this is a step in the right direction and makes sure this bug is fixed and tested for. 

If the user hasn't specified a custom source and destination we could get them from the Config and I noticed you suggest a solution for this (by setting it into the Config during load) in your gist. 

I could swear again there was an action to convert the Config over to a more structured class like you have proposed but I can't find it either. It makes perfect sense to do this... so could you raise a separate issue for this? It's quite an invasive change to be made and I'd like to do it after we move to Gradle and split up the project into sub-modules.

**Comment by ancho** [comment]
Sure. It's on my list....
