### ISSUE TITLE
All jbake-core dependencies are forced on you when used in another Maven project

### ISSUE THREAD

**Issue by jonbullock** [jbake-org/jbake#437]
Dependencies that provide content format support and template engine support were optional prior to 2.6.0 but are now forced on you when you include jbake-core in a project (as jbake-maven-plugin does) so you can't include just the dependencies that you require (i.e. include Freemarker but not Groovy).

Had a quick search and came across this: https://github.com/gradle/gradle/issues/867

**Comment by manikmagar** [comment]
Could that be the reason for binary file size difference? 2.6.0 download size is 69MB, compared to 2.5.1 having 40MB only.

**Comment by ancho** [comment]
ah. honestly I wasn't aware of the optional maven dependencies while switching to gradle. so the nebula plugin seems the way to go.

as for the size difference. we had a few dependency changes since 2.5.1. asciidoctorj-diagram and felxmark (as replacement for pegdown).

See directory and file sizes for [2.5.1](https://paste.rs/3gZ) and [2.6.0](https://paste.rs/Joa) and the [dependency graph](https://paste.rs/CcO)

We could replace `flexmark-all` with a minimal set of dependencies we really need. We don't need all extensions and converters.

**Comment by jonbullock** [comment]
I'd completely forgotten about it... only noticed as I'm updating my example projects that use the plugins for a talk and forgot to include the other dependencies and thought to myself how is it even baking a site without them being declared.
