### ISSUE TITLE
Problem with static content PR #390

### ISSUE THREAD

**Issue by gilbertoca** [jbake-org/jbake#455]
Hello guys,

First time running version 2.6.1 . The image files are copied, but the behavior is not the expected.
In the md file I have
```md
[<img src="CompileOnSave.png"  title="CompileOnSave" width="804" height="563" class="alignright size-full wp-image-701" />
```
But the final output has
```xml
<a href="CompileOnSave.png"><img src="http://localhost:8820/CompileOnSave.png" title="CompileOnSave" width="804" height="563" class="alignright size-full wp-image-701">
```
See the URL (without the /2011/05/ folder).
The image is not rendered a priory. But, to my surprise,  hover the mouse on it shows the right URL result
```xml
http://localhost:8820/2011/05/CompileOnSave.png
```
![screenshot_20180417_150013](https://user-images.githubusercontent.com/3083703/38887828-47f61a12-4250-11e8-97b8-deb60fc57bc5.png)

**Comment by manikmagar** [comment]
Hi Gilberto,

Could you try changing URL to "./CompileOnSave.png"?

See some examples here - https://jbake.org/docs/2.6.1/#images_path

Regards,
Manik Magar
https://manik.magar.me

**Comment by gilbertoca** [comment]
@jonbullock @manikmagar I think this approach is contra-intuitive, I have tons of images in my site. See this [reference on file path](https://www.w3schools.com/html/html_filepaths.asp) as well .

**Comment by msgilligan** [comment]
This seems related to my Issue https://github.com/jbake-org/jbake/issues/440

**Comment by manikmagar** [comment]
Oh ya, I agree that path with and without `./` means the same. I will take a look at that.

**Comment by ancho** [comment]
Oh. Another problem is the concatenation of `site.host` to the image URL. That leads to a problem serving the site with `jbake -s` as the image may not be present on that site when it is new.

**Comment by manikmagar** [comment]
`site.host` was appended to resolve the issues like when an article is served from other programs such as RSS readers or article is also served from other location within the site. Now, since the images have FQ url, it doesn't matter from where article is accessed. 

@ancho I think `jbake -s` ignores the site.host value from properties and uses `localhost`. There shouldn't be that problem as long as images are in the current source because locally baked and served site will have `localhost` in the URL.

I wouldn't prefer removing it at all as there was a reason for adding it. But if we make that append decision configurable, would that be helpful?  Those who have the problem of serving article from multiple locations can use append, and others may choose to ignore it. In that case, the path will be changed relative to the root of the content folder (Which may solve #440 too).

**Comment by ancho** [comment]
There is one szenario `jbake -s` does not replace the sitehost.
Running `jbake -b` and after that `jbake -s output` for example.

**Comment by manikmagar** [comment]
Ah, you are right. Since the baking has already happened, it will have site.host.   
  

  
  

  
  
>

**Comment by ancho** [comment]
Hmm. I didn't want you to remove that feature. It was just an additional case. 
And that `-s` alone does not replace the curent site.host with localhost is just another use case. The site is already rendered and publishable. We do not replace image urls and I'm not quite sure if we should do that, or just trigger another build.

**Comment by manikmagar** [comment]
WDYT about this behavior -
 
1. Do not modify image source if it starts with `http://` or `https://`.
2. Prepend Resolved root path and page URL to image source, unless it starts with `/`. Eg. `CompileOnSave.png` -> `../../2011/05/CompileOnSave.png`,  `./CompileOnSave.png` -> `../../2011/05/CompileOnSave.png` but `/CompileOnSave.png` -> `/CompileOnSave.png`
3. `img.path.prepend.host` (default `true`, otherwise it will not be backward compatible) decides if `site.host` should be prepended to image source with Point 2 above. When set to false, `site.host` will not be appended. [this along with addition root path should solve #440 ]

**Comment by gilbertoca** [comment]
Sorry @manikmagar , maybe I'm not seeing all the picture. Taking in account item 1 in your list and this [reference on file path](https://www.w3schools.com/html/html_filepaths.asp) as reference, my understanding is that all work will be/is done by the browser. So, jbake should only copy the resources along side and nothing more.

**Comment by manikmagar** [comment]
Thanks @jonbullock for the explanation.  @gilbertoca The manipulation is to ensure paths don't break, no matter from where the article is displayed.

**Comment by SiddheshRane** [comment]
I have faced a similar problem in Asciidoc files where an image source that begins with `./` resolves to post local directory but without `./` it resolves to the root of the site. Instead of prepending `./` to every image in the post, you can set `:imagesdir: .` in the post metadata.
